<?php

/**
 * This file is part of the FOSHttpCacheBundle package.
 *
 * Copyright (c) 2014 FOS Team
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace FOS\HttpCacheBundle\EventListener;

use FOS\HttpCacheBundle\CacheManager;
use FOS\HttpCacheBundle\Configuration\InvalidatePath;
use FOS\HttpCacheBundle\Configuration\InvalidateRoute;
use FOS\HttpCacheBundle\Invalidator\InvalidatorCollection;
use Symfony\Component\Console\ConsoleEvents;
use Symfony\Component\Console\Event\ConsoleEvent;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\ExpressionLanguage\SyntaxError;
use Symfony\Component\ExpressionLanguage\ExpressionLanguage;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\HttpKernel\Event\PostResponseEvent;
use Symfony\Component\Routing\RouterInterface;

/**
 * On kernel.terminate event, this event handler invalidates routes for the
 * current request and flushes the CacheManager.
 *
 * @author David de Boer <david@driebit.nl>
 */
class InvalidationSubscriber implements EventSubscriberInterface
{
    /**
     * Cache manager
     *
     * @var CacheManager
     */
    protected $cacheManager;

    /**
     * Invalidator collection
     *
     * @var InvalidatorCollection
     */
    protected $invalidators;

    /**
     * Router
     *
     * @var RouterInterface
     */
    protected $router;

    /**
     * Constructor
     *
     * @param CacheManager          $cacheManager       Cache Manager
     * @param InvalidatorCollection $invalidators       Invalidators
     * @param RouterInterface       $router             Routers
     * @param ExpressionLanguage    $expressionLanguage Expression Language
     */
    public function __construct(
        CacheManager $cacheManager,
        InvalidatorCollection $invalidators,
        RouterInterface $router,
        ExpressionLanguage $expressionLanguage = null
    )
    {
        $this->cacheManager = $cacheManager;
        $this->invalidators = $invalidators;
        $this->router = $router;
        $this->expressionLanguage = $expressionLanguage ?: new ExpressionLanguage();
    }

    /**
     * Apply invalidators and flush cache manager
     *
     * On kernel.terminate:
     * - see if any invalidators apply to the current request and, if so, add
     *   their routes to the cache manager
     * - flush the cache manager in order to send invalidation requests to the
     *   HTTP cache.
     *
     * @param PostResponseEvent $event Event
     *
     * @return array Paths that were flushed from the invalidation queue
     */
    public function onKernelTerminate(PostResponseEvent $event)
    {
        // Are there any invalidators configured for the current request route?
        $request = $event->getRequest();

        // Don't invalidate any caches if the request was unsuccessful
        $response = $event->getResponse();
        if (!$response->isSuccessful()) {
            return $this->cacheManager->flush();
        }

        // Check controller annotations
        if ($paths = $request->attributes->get('_invalidate_path')) {
            $this->invalidatePaths($paths);
        }

        if ($routes = $request->attributes->get('_invalidate_route')) {
            $this->invalidateRoutes($routes, $request);
        }

        // Check configured invalidators
        $requestRoute = $request->attributes->get('_route');
        if (!$this->invalidators->hasInvalidatorRoute($requestRoute)) {
            return $this->cacheManager->flush();
        }

        $requestParams = $request->attributes->get('_route_params');
        $invalidators = $this->invalidators->getInvalidators($requestRoute);
        foreach ($invalidators as $invalidator) {
            foreach ($invalidator->getInvalidatedRoutes() as $route => $config) {
                $path = $this->router->generate($route, $requestParams);

                // If extra route parameters should be ignored, strip the query
                // string generated by the Symfony router from the path
                if (isset($config['ignore_extra_params'])
                    && $config['ignore_extra_params']
                    && $pos = strpos($path, '?')
                ) {
                    $path = substr($path, 0, $pos);
                }

                $this->cacheManager->invalidatePath($path);
            }
        }

        return $this->cacheManager->flush();
    }

    /**
     * Flush cache manager when kernel exception occurs
     */
    public function onKernelException()
    {
        $this->cacheManager->flush();
    }

    /**
     * Flush cache manager when console terminates or errors
     *
     * @param ConsoleEvent $event Event
     */
    public function onConsoleTerminate(ConsoleEvent $event)
    {
        $num = $this->cacheManager->flush();

        if ($num > 0 && OutputInterface::VERBOSITY_VERBOSE <= $event->getOutput()->getVerbosity()) {
            $event->getOutput()->writeln(sprintf('Sent %d invalidation request(s)', $num));
        }
    }

    /**
     * {@inheritdoc}
     */
    public static function getSubscribedEvents()
    {
        return array(
            KernelEvents::TERMINATE  => 'onKernelTerminate',
            KernelEvents::EXCEPTION  => 'onKernelException',
            ConsoleEvents::TERMINATE => 'onConsoleTerminate',
            ConsoleEvents::EXCEPTION => 'onConsoleTerminate'
        );
    }

    /**
     * Invalidate paths from annotations
     *
     * @param array|InvalidatePath[] $pathConfigurations
     *
     * @return InvalidationSubscriber self Object
     */
    protected function invalidatePaths(array $pathConfigurations)
    {
        foreach ($pathConfigurations as $pathConfiguration) {
            foreach ($pathConfiguration->getPaths() as $path) {
                $this->cacheManager->invalidatePath($path);
            }
        }

        return $this;
    }

    /**
     * Invalidate routes from annotations
     *
     * @param array|InvalidateRoute[] $routes
     * @param Request                 $request
     *
     * @return InvalidationSubscriber self Object
     */
    protected function invalidateRoutes(array $routes, Request $request)
    {
        foreach ($routes as $route) {
            $params = array();

            if (null !== $route->getParams()) {
                // Iterate over route params and try to evaluate their values
                foreach ($route->getParams() as $key => $value) {
                    try {
                        $value = $this->expressionLanguage->evaluate($value, $request->attributes->all());
                    } catch (SyntaxError $e) {
                        // If a syntax error occurred, we assume the param was
                        // no expression
                    }

                    $params[$key] = $value;
                }
            }

            $this->cacheManager->invalidateRoute($route->getName(), $params);
        }

        return $this;
    }
}
